/**
 * Nhãn tiếng Việt cho khoá cấu hình của tool (Plan #53 QĐ-9). Catalog dựng trường từ `configSchema`
 * của adapter và chỉ có KHOÁ (`retentionDays`, `owner`…); form trước đây in nguyên khoá làm nhãn.
 *
 * Một bảng theo khoá, không theo tool: cùng một khoá mang cùng một nghĩa ở mọi tool (`storageGb` ở 21
 * tool). Khoá gốc vẫn hiện bên cạnh bằng chữ mono — nó là thứ người dùng gặp trong tài liệu của tool.
 * `tests/config-labels.test.ts` đối chiếu bảng này với MỌI khoá trong mẫu golden của catalog: adapter
 * mới thêm khoá mà quên nhãn là test đỏ, không phải một nhãn tiếng Anh lặng lẽ lọt lên màn hình.
 */
export const CONFIG_LABELS: Readonly<Record<string, string>> = {
  accessLog: "Ghi nhật ký truy cập",
  accessToken: "Access token",
  accountId: "ID tài khoản",
  adminPassword: "Mật khẩu quản trị",
  adminUser: "Tài khoản quản trị",
  apiKey: "API key",
  apiToken: "API token",
  appKey: "Application key",
  auditIntervalSeconds: "Chu kỳ kiểm tra (giây)",
  autoApply: "Tự áp thay đổi",
  backend: "Backend lưu state",
  bufferGb: "Bộ đệm (GB)",
  cassandraVersion: "Phiên bản Cassandra",
  checkOnly: "Chỉ kiểm tra, không áp",
  clientId: "Client ID",
  clientSecret: "Client secret",
  concurrent: "Số tác vụ song song",
  concurrentScans: "Số lượt quét song song",
  cpuHourlyUsd: "Giá CPU mỗi giờ (USD)",
  credentialSeed: "Chuỗi sinh mật khẩu",
  csi: "Gắn bí mật qua CSI",
  dashboard: "Bật dashboard",
  dashboards: "Dashboard mặc định của UDP",
  dataIngestToken: "Token đẩy dữ liệu",
  directory: "Thư mục quét",
  dockerPort: "Cổng Docker",
  driver: "Driver",
  enforcerToken: "Token của enforcer",
  environmentUrl: "URL môi trường",
  excludeSystemNamespaces: "Bỏ qua namespace hệ thống",
  externalUrl: "URL công khai",
  failOn: "Chặn khi mức nghiêm trọng từ",
  failOnWarnings: "Chặn khi có cảnh báo",
  failurePolicy: "Khi webhook lỗi",
  frameworks: "Framework kiểm tra",
  gateway: "Gateway",
  gcpServiceAccount: "Service account GCP",
  gitProvider: "Nhà cung cấp Git",
  gitlabUrl: "URL GitLab",
  googleServiceAccount: "Service account Google",
  grafana: "Kèm Grafana",
  groups: "Nhóm API",
  hecEndpoint: "Địa chỉ HEC",
  hecToken: "HEC token",
  highAvailability: "Chạy nhiều bản (HA)",
  ignoreUnfixed: "Bỏ qua lỗ hổng chưa có bản vá",
  index: "Index",
  ingressClass: "Ingress class",
  injector: "Bơm bí mật vào pod",
  integrationId: "ID tích hợp",
  intervalMinutes: "Chu kỳ đồng bộ (phút)",
  inventory: "Inventory",
  issuerCertPem: "Chứng chỉ issuer (PEM)",
  issuerKeyPem: "Khoá issuer (PEM)",
  kayenta: "Phân tích canary bằng Kayenta",
  keyRenewDays: "Xoay khoá sau (ngày)",
  keyVaultName: "Tên Key Vault",
  kibana: "Kèm Kibana",
  kubecostToken: "Token Kubecost",
  licenseKey: "License key",
  location: "Vị trí",
  lowDataMode: "Chế độ ít dữ liệu",
  maxHosts: "Số host tối đa",
  maxSpans: "Số span tối đa",
  minimumPriority: "Mức ưu tiên tối thiểu",
  mode: "Chế độ",
  mongodbVersion: "Phiên bản MongoDB",
  mysqlVersion: "Phiên bản MySQL",
  namespace: "Namespace",
  nodeCount: "Số node",
  onlyFixed: "Chỉ báo lỗ hổng đã có bản vá",
  owner: "Chủ sở hữu",
  path: "Đường dẫn trong repo",
  playbook: "Playbook",
  podSecurityStandard: "Chuẩn bảo mật pod",
  postgresVersion: "Phiên bản PostgreSQL",
  pricing: "Bảng giá",
  productionReplicas: "Số bản ở production",
  projectId: "ID project",
  projectPath: "Đường dẫn project",
  projectSlug: "Slug project",
  prometheusUrl: "URL Prometheus",
  prometheusUser: "Tài khoản Prometheus",
  providers: "Provider",
  pullPassword: "Mật khẩu kéo image",
  pullRobotName: "Tên robot kéo image",
  pullRobotSecret: "Bí mật robot kéo image",
  pullToken: "Token kéo image",
  pullUser: "Tài khoản kéo image",
  ramGiBHourlyUsd: "Giá RAM mỗi GiB mỗi giờ (USD)",
  redisVersion: "Phiên bản Redis",
  region: "Vùng",
  registryName: "Tên registry",
  replicas: "Số bản",
  repoUrl: "URL repo",
  repository: "Repository",
  repositoryPrefix: "Tiền tố repository",
  retentionDays: "Giữ dữ liệu (ngày)",
  retentionHours: "Giữ dữ liệu (giờ)",
  revision: "Nhánh hoặc tag",
  roleArn: "ARN của role",
  rotationPollSeconds: "Chu kỳ đọc lại bí mật (giây)",
  rpcSecret: "RPC secret",
  runtime: "Runtime",
  serverHost: "Địa chỉ máy chủ",
  servers: "Số máy chủ",
  severities: "Mức nghiêm trọng",
  site: "Site",
  slackWebhook: "Webhook Slack",
  softFail: "Chỉ cảnh báo, không chặn",
  storageGb: "Dung lượng đĩa (GB)",
  subscriptionId: "ID subscription",
  syncPolicy: "Chính sách đồng bộ",
  targets: "Địa chỉ quét",
  tenantId: "ID tenant",
  token: "Token",
  tokenName: "Tên token",
  tokenPassword: "Mật khẩu token",
  tracingSamplingPercent: "Tỉ lệ lấy mẫu trace (%)",
  trustAnchorPem: "Trust anchor (PEM)",
  useVault: "Dùng Vault",
  userKey: "User key",
  username: "Tên đăng nhập",
  validationFailureAction: "Khi policy không đạt",
  version: "Phiên bản",
  webhook: "Bật webhook",
  workingDirectory: "Thư mục làm việc",
};

/** Nhãn của một khoá; khoá chưa có nhãn (chỉ lọt khi test bị bỏ qua) hiện nguyên khoá */
export const configLabel = (key: string): string => CONFIG_LABELS[key] ?? key;
